"""empty message

Revision ID: 5320ff903eff
Revises: None
Create Date: 2016-08-10 06:34:54.656039

"""

# revision identifiers, used by Alembic.
revision = '5320ff903eff'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approxkeywordsprof',
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('subprofession', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_index(op.f('ix_approxkeywordsprof_profession'), 'approxkeywordsprof', ['profession'], unique=False)
    op.create_table('conversationhasmessages',
    sa.Column('convId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('messageId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('convId', 'messageId')
    )
    op.create_table('conversations',
    sa.Column('convId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('totalMessages', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('user1', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('user2', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('isConversationOpen', sa.Boolean(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('stripeCust', sa.String(length=1000), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('systemMessage', sa.Boolean(), nullable=True),
    sa.Column('price', mysql.BIGINT(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('convId')
    )
    op.create_table('credentials',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('worksAt', sa.String(length=1000), nullable=True),
    sa.Column('workstartdate', sa.String(length=1000), nullable=True),
    sa.Column('workenddate', sa.String(length=1000), nullable=True),
    sa.Column('specials', sa.String(length=1000), nullable=True),
    sa.Column('languages', sa.String(length=1000), nullable=True),
    sa.Column('degrees', sa.String(length=1000), nullable=True),
    sa.Column('schools', sa.String(length=1000), nullable=True),
    sa.Column('courses', sa.String(length=1000), nullable=True),
    sa.Column('gradyear', sa.String(length=1000), nullable=True),
    sa.Column('jobtitle', sa.String(length=1000), nullable=True),
    sa.Column('images', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('exactkeywordsprof',
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('subprofession', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_index(op.f('ix_exactkeywordsprof_profession'), 'exactkeywordsprof', ['profession'], unique=False)
    op.create_table('inbox',
    sa.Column('userId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('convId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('hasUnread', sa.Boolean(), nullable=True),
    sa.Column('typedText', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('userId', 'convId')
    )
    op.create_table('keywords',
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('prof', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_table('messages',
    sa.Column('messageId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('fromUser', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('toUser', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('hasAttachment', sa.Boolean(), nullable=True),
    sa.Column('attachmentUrl1', sa.String(length=1000), nullable=True),
    sa.Column('attachmentUrl2', sa.String(length=1000), nullable=True),
    sa.Column('isUnread', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('messageId')
    )
    op.create_table('password_token',
    sa.Column('userId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('profconsulted',
    sa.Column('userid', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('profid', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('userid', 'profid')
    )
    op.create_table('profession',
    sa.Column('professionId', sa.Integer(), nullable=False),
    sa.Column('professionName', sa.String(length=100), nullable=True),
    sa.Column('subprofessions', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('professionId')
    )
    op.create_index(op.f('ix_profession_professionName'), 'profession', ['professionName'], unique=False)
    op.create_table('professionalRatings',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('subprofession', sa.String(length=100), nullable=True),
    sa.Column('numVoiceCalls', sa.Integer(), nullable=True),
    sa.Column('numVideoCalls', sa.Integer(), nullable=True),
    sa.Column('numQuestionAnswered', sa.Integer(), nullable=True),
    sa.Column('num1star', sa.Integer(), nullable=True),
    sa.Column('num2star', sa.Integer(), nullable=True),
    sa.Column('num3star', sa.Integer(), nullable=True),
    sa.Column('num4star', sa.Integer(), nullable=True),
    sa.Column('num5star', sa.Integer(), nullable=True),
    sa.Column('avgRating', sa.Float(), nullable=True),
    sa.Column('totalReviews', sa.Float(), nullable=True),
    sa.Column('numMissedAppoints', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_professionalRatings_profession'), 'professionalRatings', ['profession'], unique=False)
    op.create_index(op.f('ix_professionalRatings_subprofession'), 'professionalRatings', ['subprofession'], unique=False)
    op.create_table('professionals',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('subprofession', sa.String(length=100), nullable=True),
    sa.Column('acceptsQandA', sa.Boolean(), nullable=True),
    sa.Column('acceptsVoice', sa.Boolean(), nullable=True),
    sa.Column('acceptsVideo', sa.Boolean(), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.Column('readyServe', sa.Boolean(), nullable=True),
    sa.Column('freeConsult', sa.Boolean(), nullable=True),
    sa.Column('firstFree', sa.Boolean(), nullable=True),
    sa.Column('voiceRate', sa.Float(), nullable=True),
    sa.Column('videoRate', sa.Float(), nullable=True),
    sa.Column('questionRate', sa.Float(), nullable=True),
    sa.Column('backgroundCheck', sa.Boolean(), nullable=True),
    sa.Column('businessCheck', sa.Boolean(), nullable=True),
    sa.Column('aboutMe', sa.UnicodeText(), nullable=True),
    sa.Column('receiveSms', sa.Boolean(), nullable=True),
    sa.Column('mazeId', sa.String(length=256), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_professionals_mazeId'), 'professionals', ['mazeId'], unique=False)
    op.create_index(op.f('ix_professionals_profession'), 'professionals', ['profession'], unique=False)
    op.create_index(op.f('ix_professionals_subprofession'), 'professionals', ['subprofession'], unique=False)
    op.create_table('profhaskeywords',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('userId', 'keyword')
    )
    op.create_table('proftimeslots',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('monstart', sa.UnicodeText(), nullable=True),
    sa.Column('monend', sa.UnicodeText(), nullable=True),
    sa.Column('tuesstart', sa.UnicodeText(), nullable=True),
    sa.Column('tuesend', sa.UnicodeText(), nullable=True),
    sa.Column('wedstart', sa.UnicodeText(), nullable=True),
    sa.Column('wedend', sa.UnicodeText(), nullable=True),
    sa.Column('thursstart', sa.UnicodeText(), nullable=True),
    sa.Column('thursend', sa.UnicodeText(), nullable=True),
    sa.Column('fristart', sa.UnicodeText(), nullable=True),
    sa.Column('friend', sa.UnicodeText(), nullable=True),
    sa.Column('satstart', sa.UnicodeText(), nullable=True),
    sa.Column('satend', sa.UnicodeText(), nullable=True),
    sa.Column('sunstart', sa.UnicodeText(), nullable=True),
    sa.Column('sunend', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('reviews',
    sa.Column('reviewId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('fromUser', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('toUser', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('timeOfReview', sa.DateTime(), nullable=True),
    sa.Column('reviewTitle', sa.String(length=50), nullable=True),
    sa.Column('stars', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('isRejected', sa.Boolean(), nullable=True),
    sa.Column('rejectReason', sa.UnicodeText(), nullable=True),
    sa.Column('reviewText', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('reviewId')
    )
    op.create_table('subprofession',
    sa.Column('professionId', sa.Integer(), nullable=False),
    sa.Column('professionName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('professionId')
    )
    op.create_index(op.f('ix_subprofession_professionName'), 'subprofession', ['professionName'], unique=False)
    op.create_table('twiliocalls',
    sa.Column('appointId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('fromEndpoint', sa.String(length=100), nullable=True),
    sa.Column('toEndpoint', sa.String(length=100), nullable=True),
    sa.Column('fromUser', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('toUser', mysql.BIGINT(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('appointId')
    )
    op.create_table('userAttributes',
    sa.Column('userId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('noOfQuestAsked', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('noOfVoiceCalls', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('noOfVideoCalls', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('noOfTimesPaid', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('noOfReviewsReqs', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('totalInboxNotifications', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('totalApptmentNotifications', mysql.BIGINT(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('users',
    sa.Column('userId', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('phoneNumber', sa.String(length=24), nullable=True),
    sa.Column('emailId', sa.String(length=120), nullable=True),
    sa.Column('pwdhash', sa.String(length=1000), nullable=True),
    sa.Column('address1', sa.String(length=1000), nullable=True),
    sa.Column('address2', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=54), nullable=True),
    sa.Column('state', sa.String(length=54), nullable=True),
    sa.Column('country', sa.String(length=54), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('ethnicity', sa.String(length=54), nullable=True),
    sa.Column('isOnline', sa.Boolean(), nullable=True),
    sa.Column('lastOnline', sa.DateTime(), nullable=True),
    sa.Column('isProfessional', sa.Boolean(), nullable=True),
    sa.Column('profilePicture', sa.String(length=256), nullable=True),
    sa.Column('profession', sa.String(length=256), nullable=True),
    sa.Column('subprofession', sa.String(length=256), nullable=True),
    sa.Column('isEmailVerified', sa.Boolean(), nullable=True),
    sa.Column('isPhoneVerified', sa.Boolean(), nullable=True),
    sa.Column('phoneCode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('emailId')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('userAttributes')
    op.drop_table('twiliocalls')
    op.drop_index(op.f('ix_subprofession_professionName'), table_name='subprofession')
    op.drop_table('subprofession')
    op.drop_table('reviews')
    op.drop_table('proftimeslots')
    op.drop_table('profhaskeywords')
    op.drop_index(op.f('ix_professionals_subprofession'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_profession'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_mazeId'), table_name='professionals')
    op.drop_table('professionals')
    op.drop_index(op.f('ix_professionalRatings_subprofession'), table_name='professionalRatings')
    op.drop_index(op.f('ix_professionalRatings_profession'), table_name='professionalRatings')
    op.drop_table('professionalRatings')
    op.drop_index(op.f('ix_profession_professionName'), table_name='profession')
    op.drop_table('profession')
    op.drop_table('profconsulted')
    op.drop_table('password_token')
    op.drop_table('messages')
    op.drop_table('keywords')
    op.drop_table('inbox')
    op.drop_index(op.f('ix_exactkeywordsprof_profession'), table_name='exactkeywordsprof')
    op.drop_table('exactkeywordsprof')
    op.drop_table('credentials')
    op.drop_table('conversations')
    op.drop_table('conversationhasmessages')
    op.drop_index(op.f('ix_approxkeywordsprof_profession'), table_name='approxkeywordsprof')
    op.drop_table('approxkeywordsprof')
    ### end Alembic commands ###
